
databases:
  - name: Employee-Onboarding-Portal
    databaseName: Employee-Onboarding-Portal
    user: Rohit
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rails db:migrate # Run migrations during the build step
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Employee-Onboarding-Portal
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
